name: dailycalc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc_test: ^10.0.0
  device_info_plus: ^12.3.0
  equatable: ^2.0.7
  expressions: ^0.2.5+3
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  math_expressions: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.4.18
  test: ^1.26.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
